# Generated by Django 3.0.8 on 2020-07-20 12:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='images')),
                ('url', models.URLField(max_length=300, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('msg', models.TextField(blank=True, null=True)),
                ('current_price', models.IntegerField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Gadget', 'Gadget'), ('Phome', 'Phone'), ('Cloth', 'Cloth'), ('Furniture', 'Furniture'), ('vehicle', 'vehicle')], default='vehicle', max_length=20)),
                ('bid', models.IntegerField(default=models.IntegerField(blank=True, null=True), validators=[django.core.validators.MinValueValidator(limit_value=models.IntegerField(blank=True, null=True))])),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Mylist')),
            ],
        ),
        migrations.CreateModel(
            name='MyBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.IntegerField(blank=True, null=True)),
                ('bid', models.IntegerField(default=models.IntegerField(blank=True, null=True), validators=[django.core.validators.MinValueValidator(limit_value=models.IntegerField(blank=True, null=True))])),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('bid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Mylist')),
            ],
        ),
    ]
