# Generated by Django 3.0.8 on 2020-07-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_mybid_mycomment_mylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybid',
            name='bid',
            field=models.IntegerField(default=models.IntegerField(blank=True, null=True)),
        ),
    ]
