# Generated by Django 3.0.8 on 2020-07-20 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200720_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycomment',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.Mylist'),
        ),
    ]
