# Generated by Django 3.0.8 on 2020-07-20 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20200720_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycomment',
            old_name='commented_by',
            new_name='user',
        ),
    ]
