# Generated by Django 3.0.8 on 2020-07-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20200720_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycomment',
            name='bid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
