# Generated by Django 3.0.8 on 2020-07-22 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_auto_20200722_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='category',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='category',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='category',
            name='msg',
        ),
        migrations.RemoveField(
            model_name='category',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='category',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='category',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='msg',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='url',
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
