# Generated by Django 3.0.8 on 2020-07-22 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_auto_20200722_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='auctions.Mylist'),
            preserve_default=False,
        ),
    ]
