# Generated by Django 3.0.8 on 2020-07-22 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
