# Generated by Django 3.0.8 on 2020-07-22 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_auto_20200722_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycomment',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='auctions.Mylist'),
        ),
    ]
