# Generated by Django 3.0.8 on 2020-07-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_auto_20200722_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycomment',
            name='user',
        ),
    ]
