# Generated by Django 3.0.8 on 2020-07-22 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_remove_mycomment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycomment',
            name='commented_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
