# Generated by Django 3.0.8 on 2020-07-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_mycomment_commented_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylist',
            name='category',
            field=models.CharField(choices=[('Gadget', 'Gadget'), ('Phone', 'Phone'), ('Cloth', 'Cloth'), ('Furniture', 'Furniture'), ('vehicle', 'vehicle')], default='vehicle', max_length=20),
        ),
    ]
