# Generated by Django 3.0.8 on 2020-07-23 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0035_auto_20200723_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycomment',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auctions.Mylist'),
        ),
    ]
