# Generated by Django 3.0.8 on 2020-07-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0038_auto_20200723_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybid',
            name='listing',
        ),
    ]
