# Generated by Django 3.0.8 on 2020-07-23 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0039_remove_mybid_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycomment',
            name='commented_by',
        ),
    ]
