# Generated by Django 3.0.8 on 2020-07-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0040_remove_mycomment_commented_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylist',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
