# Generated by Django 3.0.8 on 2020-07-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0043_mycomment_commented_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mylist',
            name='bid_by',
        ),
    ]
