# Generated by Django 3.0.8 on 2020-07-25 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0046_remove_mycomment_commented_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylist',
            name='bid_by',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='mylist2', to=settings.AUTH_USER_MODEL),
        ),
    ]
